### ISSUE TITLE
Kraken points bug

### ISSUE THREAD

**Issue by Phigz** [EOUCS344Sp15/ReleaseTheKraken#32]
The kraken point system currently allows for the point to go above the required amount

**Comment by Dalton-Baird** [comment]
This is not a bug.  You can get as many points as you can.  The points bar just shows how many you need to get to release the kraken.  The points bar is set up to stop filling up when you get enough points to release the kraken, otherwise it would keep on going across the screen.  Maybe this should be more clear though...
