### ISSUE TITLE
Allow hero to pick up PowerUp on collision

### ISSUE THREAD

**Issue by tarstarkes** [EOUCS344Sp15/ReleaseTheKraken#6]
When the hero sprite collides with the PowerUp sprite, PowerUp sprite should disappear and the Power-Up should be added to the UI and be usable.

**Comment by Dalton-Baird** [comment]
I got the Box2D PhysicsContactListener set up and working with everything else.  In order to test it, I made it so you can pick up the power ups on collision.  I would have let you do it, but I was setting up the physics and using the contact listener is pretty difficult.  I also already had most of the code for this from my CS 310 app.  This also allowed for me to test entity removal, which has changed a lot with the addition of Box2D physics.  

Power ups still don't have a spawning system.  I'm not going to do that, you guys can.  Right now, four power ups are hardcoded to spawn in the GameWorld's constructor.
